### ISSUE TITLE
Static devices are being listed twice in the device list

### ISSUE THREAD

**Issue by abrenoch** [d8ahazard/Phlex#244] opened 2017-12-08 16:33 UTC
Hey great update recently @d8ahazard!

This seems like it should be a simple fix, but the devices I add manually (thanks by the way, it works great) are showing up in the device selector menu twice. It appears they are the exact same per the token in the returned JSON, so they are probably just getting parsed twice somewhere!

Just wanted to give you a heads up!

Also, the adjustment to matching titles (like "the punisher" vs "marvel's: the punisher") works really well too. Thanks for the improvements!

**Comment by d8ahazard** [comment] 2017-12-08 16:41
Hehe, glad you're enjoying them.  Yeah, I know where the issue is with dupe static devices. Basically, I thought I'd be clever and try to avoid a full device refresh when a static device is changed/etc., but the method I created to do so interferes with full device scans, hence the duplicates. 

I'll take a look at this shortly, going around today trying to squash as many issues as I can.

**Comment by d8ahazard** [comment] 2017-12-08 21:59
Fixed with f925fee.

**Closed by d8ahazard** 2017-12-08 22:00 UTC
