### ISSUE TITLE
Undefined index @attributes util line 669

### ISSUE THREAD

**Issue by DanDon** [d8ahazard/Phlex#212] opened 2017-11-21 08:38 UTC
I receive this error on a fresh install on Windows with apache server through Xampp ... installation all went smooth....

`Notice: Undefined index: @attributes in C:\xampp\htdocs\phlex\util.php on line 669
 ERROR`

**Comment by abrenoch** [comment] 2017-11-21 15:07
Duplicate of https://github.com/d8ahazard/Phlex/issues/209

**Comment by d8ahazard** [comment] 2017-11-21 16:16
Fixed.

**Closed by d8ahazard** 2017-11-21 16:16 UTC
