### ISSUE TITLE
Playback not working

### ISSUE THREAD

**Issue by kilgil27** [d8ahazard/Phlex#252] opened 2017-12-14 01:59 UTC
Hello,

I am able to tell my google home to play a movie or tv show from plex on one of my chromecasts, it shows up in the feed on the Phlex homepage, and Plex launches like it's going to play, but it just sits on the Plex logo spinning, and never actually plays anything. I also get the following error in the logs:

Invalid API Token, forcing logout.
Thu, 14 Dec 2017 02:55:16 +0100api.php
ERROR: Unauthenticated access detected. Originating IP
Thu, 14 Dec 2017 02:55:16 +0100api.php
Sorry, couldn't validate user.
Thu, 14 Dec 2017 02:55:16 +0100api.php
INCOMING REQUEST!!

any idea how I can fix this? I feel like I'm so close!

**Comment by fun4stuff** [comment] 2017-12-14 13:51
I'm getting the same error messages. It's continuously generating new API tokens for some of us. After I get a new API token, I can usually get it to work for awhile (until i get the above error messages) by clicking the "link google" in the phlex settings.

**Comment by kilgil27** [comment] 2017-12-14 16:50
I'm running it on Windows 10, installed with xampp

**Comment by d8ahazard** [comment] 2017-12-14 19:52
I've done two things to try and sort this out:

One, for docker, I've updated the image with a script to change permissions
so that writing to the config file is not an issue.

Two, I've added a lot more logging in regards to the API Token generation
and what is calling it, etc.

So, if you're still having issues after the latest updates (You'll need to
re-pull/update your docker image, which will update Phlex if on Docker),
grab the full Phlex.log.php file and send it to me via email at the donate
address listed in the project readme.

**Comment by fun4stuff** [comment] 2017-12-14 21:09
So far, it seems to be working better for me. I can log out and back in and the API token is staying the same.

**Comment by kilgil27** [comment] 2017-12-15 05:02
Well I updated (actually just started over from scratch) and now I can't even log in, I get the following error:

Warning: fopen(C:\xampp\htdocs\phlex\logs\Phlex.log.php): failed to open stream: Permission denied in C:\xampp\htdocs\phlex\util.php on line 441

**Comment by fun4stuff** [comment] 2017-12-15 12:30
I'm no longer able to log in either.

**Comment by d8ahazard** [comment] 2017-12-15 15:03
Yep.  PEBKAC error yesterday with a commit, I just pushed a fix...

**Comment by JonBlackwell** [comment] 2017-12-15 17:05
I'm having the same issue. I can't play anything on my cast devices. The Plex logo comes up with the spinner. Phlex (takes longer than it used to) responds and says it's playing. In the logs, there is a an error: Unexpected HTTP code: 400, URL: <removed url>

**Comment by Peggle2K** [comment] 2017-12-16 11:50
Same issue, as well as not being able to talk to flex through google assistant.

I'm getting this issue when trying to launch anything through the browser to my chromecast.

**Comment by Peggle2K** [comment] 2017-12-16 11:51
Note my logs are empty - literally nothing in them. Also Phlex.log.php is a directory apparently...

**Comment by Proplex** [comment] 2017-12-16 23:57
Agreeing with Peggle here. Setting up Phlex was easy and my Google Home talks with Phlex fine. However, the entire website locks up and requires a php-fpm restart to get working again when I try to cast something. Getting on-deck information works just fine. It's just casting.

```
2017/12/16 18:53:31 [error] 27222#27222: *1497 FastCGI sent in stderr: "PHP message: PHP Warning:  fopen(/var/www/plex-ga/phlex/logs/Phlex.log.php): failed to open stream: Is a directory in /var/www/plex-ga/phlex/util.php on line 441" while reading response header from upstream, [...]"
```

**Comment by darkboomba** [comment] 2017-12-17 13:35
I'm having the same issue. Google home talks to Phlex and Phlex confirms that it will play a show. It starts Plex on my chromecast but it justs keeps on loading. Using Plex on my phone works great with chromecast so it's not that. 

These are the logs I get when I try to let it play south park https://pastebin.com/cCkSUbT8 

Phlex is running on a Raspberry Pi

**Comment by fun4stuff** [comment] 2017-12-17 14:32
@darkboomba : Same here.

**Comment by tit1** [comment] 2017-12-17 17:46
I can confirm the same issue as @darkboomba 
Server information: 

- Ubuntu 16.04 LTD
- Plex server version 1.10.1.4602
- PHP version 7.1.7-1
- apache version 2.4.18

I can also confirm that my logs are empty within the the `Phlex/logs` directory, however the log items are in the apache2 error logs:

``` [Sun Dec 17 12:16:29.437214 2017] [:error] [pid 5627] [client 67.249.88.205:63475] PHP Warning:  fopen(/var/sites/phlex/logs/Phlex.log.php): failed to open stream: Is a directory in /var/sites/phlex/util.php on line 441, referer: http://phlex.######.publicvm.com/index.php
[Sun Dec 17 12:16:34.383348 2017] [:error] [pid 32212] [client 67.249.88.205:63503] PHP Warning:  fopen(/var/sites/phlex/logs/Phlex.log.php): failed to open stream: Is a directory in /var/sites/phlex/util.php on line 441, referer: http://phlex.######.publicvm.com/index.php
[Sun Dec 17 12:16:47.343393 2017] [:error] [pid 32212] [client 67.249.88.205:63503] PHP Warning:  fopen(/var/sites/phlex/logs/Phlex.log.php): failed to open stream: Is a directory in /var/sites/phlex/util.php on line 441, referer: http://phlex.######.publicvm.com/index.php
[Sun Dec 17 12:16:48.619034 2017] [:error] [pid 32115] [client 67.249.88.205:63508] PHP Warning:  fopen(/var/sites/phlex/logs/Phlex.log.php): failed to open stream: Is a directory in /var/sites/phlex/util.php on line 441, referer: http://phlex.######.publicvm.com/index.php
[Sun Dec 17 12:17:14.452388 2017] [:error] [pid 32115] [client 67.249.88.205:63508] PHP Warning:  fopen(/var/sites/phlex/logs/Phlex.log.php): failed to open stream: Is a directory in /var/sites/phlex/util.php on line 441, referer: http://phlex.######.publicvm.com/index.php
[Sun Dec 17 12:17:50.931815 2017] [:error] [pid 32115] [client 67.249.88.205:63508] PHP Warning:  fopen(/var/sites/phlex/logs/Phlex.log.php): failed to open stream: Is a directory in /var/sites/phlex/util.php on line 441, referer: http://phlex.######.publicvm.com/index.php
[Sun Dec 17 12:21:07.941603 2017] [:error] [pid 32115] [client 67.249.88.205:63508] PHP Warning:  fopen(/var/sites/phlex/logs/Phlex.log.php): failed to open stream: Is a directory in /var/sites/phlex/util.php on line 441, referer: http://phlex.######.publicvm.com/index.php```

I copied the the file `Phlex_update.log.php` and renamed it to `Plex.log.php` (deleted the same named directory first.) i tried casting again and received this in the new log file.

``` [Sun, 17 Dec 2017 12:37:03 -0500] [DEBUG] [api.php] - INCOMING REQUEST!!
[Sun, 17 Dec 2017 12:37:03 -0500] [DEBUG] [api.php] - Logging in as ######.
[Sun, 17 Dec 2017 12:37:03 -0500] [INFO] [api.php::checkSignIn] - Trying to sign into Plex.tv as ######.
[Sun, 17 Dec 2017 12:37:03 -0500] [DEBUG] [util.php::signIn] - No token or not signed in, signing into Plex.
[Sun, 17 Dec 2017 12:37:04 -0500] [DEBUG] [util.php::signIn] - Container: {"email":"######@gmail.com","id":"1653625","uuid":"7b0a35ace1173fe6","mailing_list_status":"active","thumb":"https:\/\/plex.tv\/users\/7b0a35ace1173fe6\/avatar?c=1513532224","username":"######","title":"######","cloudSyncDevice":"16911e98-9e2a-45ef-b615-6dce3abd4e5d","locale":"","authenticationToken":"######","authToken":"######","scrobbleTypes":"","restricted":"0","home":"1","guest":"0","queueEmail":"queue+LzoWcQQWaEuCkZspDZPi@save.plex.tv","queueUid":"bce3a8e8c0a43f99","hasPassword":"true","homeSize":"6","maxHomeSize":"15","rememberMe":"false","secure":"1","certificateVersion":"2"}
[Sun, 17 Dec 2017 12:37:04 -0500] [DEBUG] [util.php::cacheImage] - Function fired, caching https://plex.tv/users/7b0a35ace1173fe6/avatar?c=1513532224
[Sun, 17 Dec 2017 12:37:04 -0500] [DEBUG] [util.php::cacheImage] - Caching file.
[Sun, 17 Dec 2017 12:37:05 -0500] [DEBUG] [util.php::cacheImage] - Image retrieved successfully!
[Sun, 17 Dec 2017 12:37:05 -0500] [DEBUG] [util.php::cacheImage] - Extension detected successfully!
[Sun, 17 Dec 2017 12:37:05 -0500] [DEBUG] [util.php::cacheImage] - Success, returning cached URL: https://phlex.######.publicvm.com//img/cache/afa7c25b7bd686e40921a46f3ec72f59.jpeg
[Sun, 17 Dec 2017 12:37:05 -0500] [DEBUG] [util.php::checkSetUser] - Checking ###### against ###### and ######@gmail.com
[Sun, 17 Dec 2017 12:37:05 -0500] [DEBUG] [util.php::checkSetUser] - Found matching token for ######.
[Sun, 17 Dec 2017 12:37:05 -0500] [DEBUG] [api.php::checkSignIn] - Successfully logged in as ######.
[Sun, 17 Dec 2017 12:37:05 -0500] [INFO] [api.php::setSessionVariables] - No DVR found, checking for available devices.
[Sun, 17 Dec 2017 12:37:05 -0500] [DEBUG] [api.php] - INCOMING REQUEST!!
[Sun, 17 Dec 2017 12:37:05 -0500] [DEBUG] [api.php] - Using token from GET
[Sun, 17 Dec 2017 12:37:06 -0500] [INFO] [api.php::setSessionVariables] - No DVR found, checking for available devices.
[Sun, 17 Dec 2017 12:37:09 -0500] [DEBUG] [api.php] - INCOMING REQUEST!!
[Sun, 17 Dec 2017 12:37:09 -0500] [DEBUG] [api.php] - Using token from GET
[Sun, 17 Dec 2017 12:37:09 -0500] [INFO] [api.php::setSessionVariables] - No DVR found, checking for available devices.
[Sun, 17 Dec 2017 12:37:09 -0500] [INFO] [api.php::initialize] - New device selected. Type is plexClient. ID is d56e6d1d3b769a6a8075a82150bdd728. Name is
[Sun, 17 Dec 2017 12:37:09 -0500] [INFO] [api.php::setSessionVariables] - No DVR found, checking for available devices.
[Sun, 17 Dec 2017 12:37:45 -0500] [DEBUG] [api.php] - INCOMING REQUEST!!
[Sun, 17 Dec 2017 12:37:45 -0500] [DEBUG] [api.php] - Using token from POST
[Sun, 17 Dec 2017 12:37:45 -0500] [INFO] [api.php::setSessionVariables] - No DVR found, checking for available devices.
[Sun, 17 Dec 2017 12:37:45 -0500] [INFO] [api.php::parseApiCommand] - Full API.AI request: {"originalRequest":{"source":"google","version":"2","data":{"surface":{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"},{"name":"actions.capability.SCREEN_OUTPUT"},{"name":"actions.capability.WEB_BROWSER"}]},"inputs":[{"rawInputs":[{"query":"tell Flex TV to play Jingle All the Way"}],"arguments":[{"rawText":"play Jingle All the Way","textValue":"play Jingle All the Way","name":"trigger_query"},{"name":"3p_open_priority","boolValue":true},{"rawText":"play","textValue":"play","name":"action"},{"rawText":"Jingle All the Way","textValue":"Jingle All the Way","name":"command"}],"intent":"actions.intent.MAIN"}],"user":{"lastSeen":"2017-12-17T17:15:29Z","accessToken":"######","locale":"en-US","userId":"######-######-######"},"conversation":{"conversationId":"1513532264769","type":"NEW"},"availableSurfaces":[{"capabilities":[{"name":"actions.capability.AUDIO_OUTPUT"},{"name":"actions.capability.SCREEN_OUTPUT"}]}]}},"id":"38020bb9-c74d-4eec-b2e2-bbeb636221ed","timestamp":"2017-12-17T17:37:44.902Z","lang":"en-us","result":{"source":"agent","resolvedQuery":"play Jingle All the Way","action":"Playmedia","parameters":{"action":"play","command":"Jingle All the Way"},"contexts":[{"name":"promptfortitle","parameters":{"command":"Jingle All the Way","command.original":"Jingle All the Way","action.original":"play","action":"play"},"lifespan":3},{"name":"waitforplayer","parameters":{"command":"Jingle All the Way","command.original":"Jingle All the Way","action.original":"play","action":"play"},"lifespan":2},{"name":"google_assistant_welcome","parameters":{"command":"Jingle All the Way","command.original":"Jingle All the Way","action.original":"play","action":"play"},"lifespan":5},{"name":"actions_capability_screen_output","parameters":{"command":"Jingle All the Way","command.original":"Jingle All the Way","action.original":"play","action":"play"}},{"name":"yes","parameters":{"command":"Jingle All the Way","command.original":"Jingle All the Way","action.original":"play","action":"play"},"lifespan":3},{"name":"actions_capability_audio_output","parameters":{"command":"Jingle All the Way","command.original":"Jingle All the Way","action.original":"play","action":"play"}},{"name":"playmedia-followup","parameters":{"command":"Jingle All the Way","command.original":"Jingle All the Way","action.original":"play","action":"play"},"lifespan":2},{"name":"actions_capability_web_browser","parameters":{"command":"Jingle All the Way","command.original":"Jingle All the Way","action.original":"play","action":"play"}}],"metadata":{"matchedParameters":[{"dataType":"@Triggers","name":"action","value":"$action"},{"dataType":"@sys.any","name":"command","value":"$command"}],"intentName":"PlayMedia","intentId":"b8151275-afad-4f3f-bd9a-3a17f390cb75","webhookUsed":"true","webhookForSlotFillingUsed":"false","nluResponseTime":46},"fulfillment":{"messages":[[]]},"score":1},"status":{"code":200,"errorType":"success"},"sessionId":"1513532264769"}
[Sun, 17 Dec 2017 12:37:45 -0500] [INFO] [api.php::parseApiCommand] - Final params should be an action of play, a command of jingle all the way, a type of , and a control of .
[Sun, 17 Dec 2017 12:37:45 -0500] [INFO] [api.php::parseApiCommand] - Final media result: false
[Sun, 17 Dec 2017 12:37:45 -0500] [INFO] [api.php::plexSearch] - URL is https://192-168-0-5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXX:32400/hubs/search?query=jingle+all+way&limit=30&X-Plex-Token=XXXXXXXXXXXXXXXXXXXX
[Sun, 17 Dec 2017 12:37:45 -0500] [INFO] [api.php::fetchMediaExtra] - URL is https://192-168-0-5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXX:32400/library/metadata/338089?X-Plex-Token=XXXXXXXXXXXXXXXXXXXX
[Sun, 17 Dec 2017 12:37:45 -0500] [INFO] [api.php::fetchMediaExtra] - URL is https://192-168-0-5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXX:32400/library/metadata/81096?X-Plex-Token=XXXXXXXXXXXXXXXXXXXX
[Sun, 17 Dec 2017 12:37:46 -0500] [INFO] [api.php::fetchMediaExtra] - URL is https://192-168-0-5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXX:32400/library/metadata/?X-Plex-Token=XXXXXXXXXXXXXXXXXXXX
[Sun, 17 Dec 2017 12:37:46 -0500] [INFO] [api.php::fetchMediaExtra] - URL is https://192-168-0-5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXX:32400/library/metadata/?X-Plex-Token=XXXXXXXXXXXXXXXXXXXX
[Sun, 17 Dec 2017 12:37:46 -0500] [INFO] [api.php::plexSearch] - Return array: [{"Media":{"Part":{"id":"547014","key":"\/library\/parts\/547014\/1387568508\/file.mp4","duration":"5624618","file":"\/tank\/Movies\/Jingle All the Way (1996)\/Jingle All the Way (1996).mp4","size":"787199559","audioProfile":"lc","container":"mp4","has64bitOffsets":"0","optimizedForStreaming":"1","videoProfile":"high"},"videoResolution":"720","id":"519537","duration":"5624618","bitrate":"1120","width":"1280","height":"688","aspectRatio":"1.85","audioChannels":"2","audioCodec":"aac","videoCodec":"h264","container":"mp4","videoFrameRate":"24p","optimizedForStreaming":"1","audioProfile":"lc","has64bitOffsets":"0","videoProfile":"high"},"Genre":[{"tag":"Family"},{"tag":"Comedy"}],"Director":{"tag":"Brian Levant"},"Writer":{"tag":"Randy Kornfield"},"Country":{"tag":"USA"},"Collection":{"tag":"Jingle All the Way"},"Role":{"tag":"Arnold Schwarzenegger","0":{"tag":"Sinbad"},"1":{"tag":"Phil Hartman"}},"librarySectionTitle":"Movies","reason":"section","reasonID":"28","reasonTitle":"Movies","ratingKey":"338089","key":"\/library\/metadata\/338089","studio":"Twentieth Century Fox Film Corp","type":"movie","title":"Jingle All the Way","contentRating":"PG","rating":"1.7","audienceRating":"3.8","viewOffset":"3535564","viewCount":"2","lastViewedAt":"1513526032","year":"1996","tagline":"Two Dads, One Toy, No Prisoners.","thumb":"\/library\/metadata\/338089\/thumb\/1461437906","art":"\/library\/metadata\/338089\/art\/1461437906","duration":"5624618","originallyAvailableAt":"1996-11-22","addedAt":"1387568508","updatedAt":"1461437906","audienceRatingImage":"rottentomatoes:\/\/image.rating.spilled","chapterSource":"agent","primaryExtraKey":"\/library\/metadata\/341748","ratingImage":"rottentomatoes:\/\/image.rating.rotten","summary":"Meet Howard Langston, a salesman for a mattress company is constantly busy at his job, and he also constantly disappoints his son, after he misses his son's karate exposition, his son tells Howard that he wants for Christmas is an action figure of his son's television hero, he tries hard to to make it up to him. Unfortunately for Howard, it is Christmas Eve, and every store is sold out of Turbo Man, now Howard must travel all over town and compete with everybody else to find a Turbo Man action figure."},{"Media":{"Part":{"id":"116552","key":"\/library\/parts\/116552\/1387568508\/file.mp4","duration":"5624618","file":"\/tank\/Movies\/Jingle All the Way (1996)\/Jingle All the Way (1996).mp4","size":"787199559","audioProfile":"lc","container":"mp4","has64bitOffsets":"0","optimizedForStreaming":"1","videoProfile":"high"},"videoResolution":"720","id":"89212","duration":"5624618","bitrate":"1120","width":"1280","height":"688","aspectRatio":"1.85","audioChannels":"2","audioCodec":"aac","videoCodec":"h264","container":"mp4","videoFrameRate":"24p","optimizedForStreaming":"1","audioProfile":"lc","has64bitOffsets":"0","videoProfile":"high"},"Genre":[{"tag":"Christmas"},{"tag":"Comedy"}],"Director":{"tag":"Brian Levant"},"Writer":{"tag":"Randy Kornfield"},"Country":{"tag":"USA"},"Collection":{"tag":"Jingle All The Way"},"Role":{"tag":"Yeardley Smith","0":{"tag":"Jake Lloyd"},"1":{"tag":"Martin Mull"}},"librarySectionTitle":"Movies - New","reason":"section","reasonID":"15","reasonTitle":"Movies - New","ratingKey":"81096","key":"\/library\/metadata\/81096","studio":"Twentieth Century Fox Film Corp","type":"movie","title":"Jingle All the Way","contentRating":"PG","rating":"5.6","viewOffset":"3535564","viewCount":"2","lastViewedAt":"1513526032","year":"1996","tagline":"Two Dads, One Toy, No Prisoners.","thumb":"\/library\/metadata\/81096\/thumb\/1429285336","art":"\/library\/metadata\/81096\/art\/1429285336","duration":"5624618","originallyAvailableAt":"1996-11-16","addedAt":"1429279047","updatedAt":"1429285336","primaryExtraKey":"\/library\/metadata\/84059","summary":"Meet Howard Langston, a salesman for a mattress company is constantly busy at his job, and he also constantly disappoints his son, after he misses his son's karate exposition, his son tells Howard that he wants for Christmas is an action figure of his son's television hero, he tries hard to to make it up to him. Unfortunately for Howard, it is Christmas Eve, and every store is sold out of Turbo Man, now Howard must travel all over town and compete with everybody else to find a Turbo Man action figure."},{"key":"\/library\/sections\/28\/all?collection=72895","librarySectionID":"28","librarySectionKey":"\/library\/sections\/28","librarySectionTitle":"Movies","librarySectionType":"1","reason":"section","reasonID":"28","reasonTitle":"Movies","type":"tag","id":"72895","filter":"collection=72895","tag":"Jingle All The Way","tagType":"2","count":"1","art":null,"thumb":null},{"key":"\/library\/sections\/15\/all?collection=72895","librarySectionID":"15","librarySectionKey":"\/library\/sections\/15","librarySectionTitle":"Movies - New","librarySectionType":"1","reason":"section","reasonID":"15","reasonTitle":"Movies - New","type":"tag","id":"72895","filter":"collection=72895","tag":"Jingle All The Way","tagType":"2","count":"1","art":null,"thumb":null}]
[Sun, 17 Dec 2017 12:37:46 -0500] [INFO] [api.php::returnSpeech] - My reply is going to be 'Okay,  Playing  Jingle All the Way (1996).'.
[Sun, 17 Dec 2017 12:37:46 -0500] [INFO] [api.php::queueMedia] - URL is https://192-168-0-5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXX:32400/library/metadata/338089?X-Plex-Token=XXXXXXXXXXXXXXXXXXXX
[Sun, 17 Dec 2017 12:37:46 -0500] [INFO] [api.php::queueMedia] - URL is https://192-168-0-5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXX.XXXXXX:32400/playQueues?type=video&uri=library://83940cd6-578e-43bf-86da-154e590df467/item/%2Flibrary%2Fmetadata%2F338089&shuffle=0&repeat=0&includeChapters=1&own=1&X-Plex-Client-Identifier=bb3e7357f118f72c618163f3&X-Plex-Product=Phlex&X-Plex-Version=1.0.0&X-Plex-Platform=Web&X-Plex-Platform-Version=1.0.0&X-Plex-Device=PhlexWeb&X-Plex-Device-Name=Phlex&X-Plex-Device-Screen-Resolution=1520x707,1680x1050,1920x1080&X-Plex-Token=XXXXXXXXXXXXXXXXXXXX
[Sun, 17 Dec 2017 12:37:46 -0500] [ERROR] [util.php::curlGet] - Unexpected HTTP code: 400, URL: https://192-168-0-5.7f758dc18bdc4bda8391b9407cbe62ea.plex.direct:32400/security/token?type=delegation&scope=all&X-Plex-Product=Plex Web&X-Plex-Version=1.1.0&X-Plex-Client-Identifier=bb3e7357f118f72c618163f3&X-Plex-Platform=Chrome&X-Plex-Platform-Version=62.0&X-Plex-Sync-Version=2&X-Plex-Device=Windows&X-Plex-Device-Name=Plex Web (Chrome)&X-Plex-Device-Screen-Resolution=1680x919,1680x1050&X-Plex-Token=n9xhruWsVqoyjfC67NyJ&X-Plex-Provider-Version=1.1
[Sun, 17 Dec 2017 12:37:51 -0500] [DEBUG] [api.php] - INCOMING REQUEST!!
[Sun, 17 Dec 2017 12:37:51 -0500] [DEBUG] [api.php] - Sorry, couldn't validate user.
[Sun, 17 Dec 2017 12:37:51 -0500] [ERROR] [api.php] - ERROR: Unauthenticated access detected.  Originating IP - 192.99.197.11
[Sun, 17 Dec 2017 12:37:51 -0500] [DEBUG] [api.php] - Invalid API Token, forcing logout.
[Sun, 17 Dec 2017 12:38:14 -0500] [INFO] [api.php::fireHook] - Webhooks are enabled.
[Sun, 17 Dec 2017 12:38:14 -0500] [ERROR] [api.php::fireHook] - ERROR, no URL!
[Sun, 17 Dec 2017 12:38:14 -0500] [INFO] [api.php::playMedia] - Playback Result: {"status":"success","url":"chromecast:\/\/192.168.0.20:8009"}```

**Comment by tit1** [comment] 2017-12-20 23:50
i just wanted to comment that plex is now playing as expected. I had to do a manual update, i was 3 commits behind, but playback is now working. I have to perform a `git fetch all`, `git reset --hard origin` as there where 3-4 files that changed locally blocking a standard fetch.

**Comment by Arthrax** [comment] 2017-12-22 02:54
Since roughly a week ago, if I ask my Google Assistant to talk to Flex TV or play anything through Flex TV, it keeps giving me the error "Error 22: The requested URL returned error: 417 Expectation Failed" along with unauthorized access detected and invalid api token errors on the logs. Though I can play video by manually typing commands on the browser-side console, I cannot use Flex/Phlex with google assistant

**Comment by alexenglish** [comment] 2017-12-29 20:57
I am able to cast without issue directly from Plex, but when using Phlex to initiate the app loads on the chromecast, the loading indicator spins for a brief moment, then goes to the "ready to cast" screen. The behavior is the same, but from looking at the logs from other users, I'm not positive it is the same issue.

Here is relevant output from my log.

```
[Fri, 29 Dec 2017 12:32:14 -0800] [DEBUG] [api.php] - INCOMING REQUEST!!
[Fri, 29 Dec 2017 12:32:14 -0800] [DEBUG] [api.php] - Using token from GET
[Fri, 29 Dec 2017 12:32:14 -0800] [INFO] [api.php::setSessionVariables] - No DVR found, checking for available devices.
[Fri, 29 Dec 2017 12:32:14 -0800] [INFO] [api.php::initialize] - Incoming API request detected.
[Fri, 29 Dec 2017 12:32:15 -0800] [INFO] [api.php::parseApiCommand] - Full API.AI request: {"id":"fa006fa1-57c0-44bb-bc52-6c3dd8687703","timestamp":"2017-12-29T20:32:14.781Z","lang":"en","result":{"source":"agent","resolvedQuery":"play brick","action":"Playmedia","parameters":{"action":"play","geo-city":"Brick"},"contexts":[{"name":"promptfortitle","parameters":{"geo-city":"Brick","action.original":"play","action":"play","geo-city.original":"brick"},"lifespan":3},{"name":"waitforplayer","parameters":{"geo-city":"Brick","action.original":"play","action":"play","geo-city.original":"brick"},"lifespan":2},{"name":"google_assistant_welcome","parameters":{"geo-city":"Brick","action.original":"play","action":"play","geo-city.original":"brick"},"lifespan":5},{"name":"yes","parameters":{"geo-city":"Brick","action.original":"play","action":"play","geo-city.original":"brick"},"lifespan":3},{"name":"playmedia-followup","parameters":{"geo-city":"Brick","action.original":"play","action":"play","geo-city.original":"brick"},"lifespan":2}],"metadata":{"intentId":"b8151275-afad-4f3f-bd9a-3a17f390cb75","webhookUsed":"true","webhookForSlotFillingUsed":"false","webhookResponseTime":195,"intentName":"PlayMedia"},"fulfillment":{"messages":[[]]},"score":0.92257125569459},"status":{"code":206,"errorType":"partial_content","errorDetails":"Webhook call failed. Error: Webhook response was empty."},"sessionId":"XXXXXXXX","originalRequest":{"data":{"inputs":[{"raw_inputs":[{"query":"play brick"}]}]}}}
[Fri, 29 Dec 2017 12:32:15 -0800] [INFO] [api.php::parseApiCommand] - Final params should be an action of control, a command of play, a type of , and a control of .
[Fri, 29 Dec 2017 12:32:15 -0800] [INFO] [api.php::returnSpeech] - My reply is going to be 'Okay.'.
[Fri, 29 Dec 2017 12:32:15 -0800] [INFO] [api.php::parseControlCommand] - No command set so far, making one.
[Fri, 29 Dec 2017 12:32:18 -0800] [INFO] [api.php::sendCommand] - Command Result: {"url":"No URL","status":"success"}
```

**Comment by d8ahazard** [comment] 2018-02-09 01:49
I'd try the beta branch for now - this functionality has been heavily re-worked in the new release. While it's not finished yet, it has already been addressed in the recode, and as such, I'm going to close this issue to keep things straight for dev purposes.

You'll also need to install the cast plugin on a local Plex server.  https://github.com/d8ahazard/Cast.bundle

**Closed by d8ahazard** 2018-02-09 01:49 UTC
