### ISSUE TITLE
Notice: Undefined Index

### ISSUE THREAD

**Issue by NByz** [d8ahazard/Phlex#207] opened 2017-11-18 18:36 UTC
After freshly replacing the Phlex folder in the xampp folder, I've been getting "Notice: Undefined Index" errors, referencing body.php and api.php.  The quantities vary.

The body.php errors refer to line numbers that don't seem to exist in body.php.  My body.php only has 91 lines, but all of the error lines are between 242 and 676.  An Example:

> Notice: Undefined index: hookUrl in G:\xampp\htdocs\phlex\body.php on line 242

Probably more importantly, plexDvrUri and updateAvailable in api.php seem to be consistently undefined:

> Notice: Undefined index: plexDvrUri in G:\xampp\htdocs\phlex\api.php on line 3292
> 
> Notice: Undefined index: updateAvailable in G:\xampp\htdocs\phlex\api.php on line 3295

Any help would be appreciated.  This has been a bit of an arduous setup so far, but it all the while it has felt like success is only one change away...

**Comment by jvreeken** [comment] 2017-11-20 22:43
I have the same problem...
I updated to the latest master and it made things go wacky:

Notice: Undefined variable: _SESSION in /Users/macpro/Sites/api.php on line 4320
Notice: Undefined index: rescanTime in /Users/macpro/Sites/api.php on line 1785
Notice: Undefined index: autoUpdate in /Users/macpro/Sites/util.php on line 1800
Notice: Undefined index: useCast in /Users/macpro/Sites/api.php on line 1791
Notice: Undefined index: cleanLogs in /Users/macpro/Sites/util.php on line 495
Notice: Undefined index: noLoop in /Users/macpro/Sites/api.php on line 1799
Notice: Undefined index: cleanLogs in /Users/macpro/Sites/util.php on line 495
Notice: Undefined index: noLoop in /Users/macpro/Sites/api.php on line 1810
Notice: Undefined index: cleanLogs in /Users/macpro/Sites/util.php on line 495
Notice: Undefined index: newToken in /Users/macpro/Sites/api.php on line 74
Notice: Undefined index: newToken in /Users/macpro/Sites/api.php on line 75
Notice: Undefined index: hookUrl in /Users/macpro/Sites/body.php on line 242
Notice: Undefined index: hookPlayUrl in /Users/macpro/Sites/body.php on line 254
Notice: Undefined index: hookPausedUrl in /Users/macpro/Sites/body.php on line 267
Notice: Undefined index: hookStopUrl in /Users/macpro/Sites/body.php on line 279
Notice: Undefined index: hookFetchUrl in /Users/macpro/Sites/body.php on line 291
Notice: Undefined index: hookCustomUrl in /Users/macpro/Sites/body.php on line 303
Notice: Undefined index: hookCustomPhrase in /Users/macpro/Sites/body.php on line 307
Notice: Undefined index: uiSettingHookCustomResponse in /Users/macpro/Sites/body.php on line 309
Notice: Undefined index: plexDvrReplaceLower in /Users/macpro/Sites/body.php on line 402
Notice: Undefined index: plexDvrRecordPartials in /Users/macpro/Sites/body.php on line 408
Notice: Undefined index: dvr_endoffset in /Users/macpro/Sites/body.php on line 418
Notice: Undefined index: radarrList in /Users/macpro/Sites/api.php on line 3986
Notice: Undefined index: radarrList in /Users/macpro/Sites/api.php on line 3990
Notice: Undefined index: radarrProfile in /Users/macpro/Sites/api.php on line 3992
Notice: Undefined index: uiSettingLogupdate in /Users/macpro/Sites/body.php on line 676
Notice: Undefined index: plexDvrUri in /Users/macpro/Sites/api.php on line 3292
Notice: Undefined index: updateAvailable in /Users/macpro/Sites/api.php on line 3295

Also when I try to test sonnar or raddar it gives me an error now:
ERROR: Service name not recognized
pops up at the bottom of the screen.

**Comment by wild9** [comment] 2017-11-21 12:32
I have exactly the same issue as jvreeken

**Comment by abrenoch** [comment] 2017-11-21 15:07
Duplicate of https://github.com/d8ahazard/Phlex/issues/209

**Comment by d8ahazard** [comment] 2017-11-21 16:17
Fixed.

**Closed by d8ahazard** 2017-11-21 16:17 UTC
