### ISSUE TITLE
Does not detect Plex Media Player as a cast device

### ISSUE THREAD

**Issue by eddiezab** [d8ahazard/Phlex#40] opened 2017-04-28 12:22 UTC
I'm using a Plex Media Player on a raspberry pi however, Phlex does not detect it as a casting option.

**Comment by d8ahazard** [comment] 2017-04-28 15:25
Like, it's not listed as a player at all?

**Comment by eddiezab** [comment] 2017-04-28 16:00
That's correct. 

The UPNP returns this:
```
<n1:root xmlns:n1="urn:schemas-upnp-org:device-1-0">
<specVersion>
<major>1</major>
<minor>0</minor>
</specVersion>
<device>
<deviceType>urn:roku-com:device:player:1-0</deviceType>
<friendlyName>livingroom-htpc</friendlyName>
<manufacturer>Roku</manufacturer>
<manufacturerURL>http://www.roku.com</manufacturerURL>
<modelDescription>Roku Streaming Player Network Media</modelDescription>
<modelName>Roku 3</modelName>
<modelNumber>4200X</modelNumber>
<modelURL>http://www.roku.com</modelURL>
<serialNumber>12345678900</serialNumber>
<UDN>uuid:92bc7d6e-af16-4b32-9003-5c84db43f0a6</UDN>
<serviceList>
<service>
<serviceType>urn:roku-com:service:ecp:1</serviceType>
<serviceId>urn:roku-com:serviceId:ecp1-0</serviceId>
<controlURL/>
<eventSubURL/>
<SCPDURL>ecp_SCPD.xml</SCPDURL>
</service>
</serviceList>
</device>
</n1:root>


```

**Comment by d8ahazard** [comment] 2017-04-28 19:00
That's right - I don't think it should be listed as a "cast" device?  Currently, only actual chromecast devices and cast-certified android devices will be shown as a cast receiver...this is by design.

However, you should still have PMP as a client in Phlex, provided PMP is up and running on the rasPi.

**Comment by eddiezab** [comment] 2017-04-28 19:22
Ok, I think I might be confused by your statement. In the select the "Player To Control" dropdown, should the PMP on the raspberry pi be listed? Because in my instance, it currently is not listed as a player to control.

**Comment by d8ahazard** [comment] 2017-05-08 16:37
@eddiezab - If you could please, try updating Phlex and taking a look at your list of devices, let me know if this is resolved with the latest changes from the past few days.

**Comment by eddiezab** [comment] 2017-05-08 23:14
Yes! Fantastic. Thanks for the awesome work and the quick turn-around!

**Closed** 2017-05-09 02:35 UTC
