### ISSUE TITLE
Having to Re-Link to google every few hours (~6 hrs)

### ISSUE THREAD

**Issue by fun4stuff** [d8ahazard/Phlex#248] opened 2017-12-11 02:14 UTC
I'm running phlex in a docker container on my synology NAS.
Is Phlex using http or https? Http

I finally got it up and running. Works well. However, I've found that after several hours I will get an error from google: "An error has occurred. Please report the following message to the developer:" (It's blank: no error message).

I can usually fix it by going into the phlex gui settings and choosing "Link google". Some of the times I have also had to restart the container as well. Some of the times I have had to resort to deleting everything and reinstall though.

Any suggestions?

**Comment by fun4stuff** [comment] 2017-12-11 15:41
So this morning, same issues. But this time when I click "link google" the page returns "Unable to connect to Client at http://fun4stuff.synology.me:5666/, please check the setting for 'Public Address' in the Phlex UI." rather than the Nicolas cage pic. 

So this tells me I will have to restart or reinstall to get it to work again.

**Comment by fun4stuff** [comment] 2017-12-11 16:33
So this time I had to restart the docker container, go into google assistant app on my phone and unlink/relink flex tv, then click "link google" in the phlex GUI settings. This solved it. But after a few hours, it will require me to repeat this process.

**Comment by d8ahazard** [comment] 2017-12-14 21:57
Closing as this is a duplicate of a few other issues, trying to group them up.

**Closed by d8ahazard** 2017-12-14 21:57 UTC
