### ISSUE TITLE
Apple TV 4 not available as Player

### ISSUE THREAD

**Issue by jmeehan11** [d8ahazard/Phlex#15] opened 2017-04-02 03:25 UTC
Apple TV 4 is not listed as an available player.
So far I see the following as players (all working)

-ios10 plex app
-chromecast
-chromecast ultra
-plex web (chrome)

I know the apple tv app is advertising as a player as I can see it as an available player on the plex.tv web app.

**Comment by d8ahazard** [comment] 2017-05-02 17:55
Hello, I've reworked the device fetching method, could you please update and let me know if your ATV is showing in the list of devices?

**Comment by d8ahazard** [comment] 2017-05-08 16:23
@jmeehan11 -

I'm going to close this, as the issue is somewhat old and I've done extensive reworking to the device fetching stuff.  

If you're still having issues, feel free to open a new issue.  Please include the contents of the following URL:

https://plex.tv/api/resources?includeHttps=1&X-Plex-Token=<YOUR PLEX TOKEN>

You can view your Phlex logs to discern what your plex token should be.  

Also, be aware that you want to remove any "accessToken" fields and "address/uri" fields that may share personal info with the world before posting.

**Closed by d8ahazard** 2017-05-08 16:23 UTC
